// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taski_Website.Data;

#nullable disable

namespace Taski_Website.Migrations
{
    [DbContext(typeof(WebseiteContext))]
    [Migration("20240124211712_NewUpdate2")]
    partial class NewUpdate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("Taski_Website.Model.TaskiTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            DueDate = new DateTime(2024, 1, 24, 22, 17, 11, 871, DateTimeKind.Local).AddTicks(2741),
                            TaskDescription = "Big Task 1",
                            TaskName = "Test Task 1"
                        },
                        new
                        {
                            TaskId = 2,
                            DueDate = new DateTime(2024, 1, 24, 22, 17, 11, 871, DateTimeKind.Local).AddTicks(2792),
                            TaskDescription = "Big Task",
                            TaskName = "Test Task 2"
                        });
                });

            modelBuilder.Entity("Taski_Website.Model.TaskiUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "Muster_Teacher@Taski.de",
                            Password = "123",
                            Role = "Teacher"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "Muster_Student@Taski.de",
                            Password = "123",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("Taski_Website.Model.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTask");
                });

            modelBuilder.Entity("Taski_Website.Model.UserTask", b =>
                {
                    b.HasOne("Taski_Website.Model.TaskiTask", "Task")
                        .WithMany("UserTask")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taski_Website.Model.TaskiUser", "User")
                        .WithMany("UserTask")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Taski_Website.Model.TaskiTask", b =>
                {
                    b.Navigation("UserTask");
                });

            modelBuilder.Entity("Taski_Website.Model.TaskiUser", b =>
                {
                    b.Navigation("UserTask");
                });
#pragma warning restore 612, 618
        }
    }
}
